---
# <center> <b> TTL LAB 7: Numpy Rest in Python </b>

### Name: Ayush Priyam
### Roll: 20051933
### Date: 28th Feb 2023

---


#### Q1. Write a NumPy program to concatenate element-wise two arrays of string.

In [48]:
import numpy as np
x1 = np.array(['Python', 'PHP'], dtype=str)
x2 = np.array([' Java', ' C++'], dtype=str)
print("Arrays:", x1, x2)
print("Concatenated array: ", np.char.add(x1, x2))


Arrays: ['Python' 'PHP'] [' Java' ' C++']
Concatenated array:  ['Python Java' 'PHP C++']


----
#### Q2. Write a NumPy program to split the element of a given array with spaces.

In [49]:
arr = np.array(['Python PHP Java C++'], dtype=str)
print("Original Arr:")
print(arr)
print("After Split : ", np.char.split(arr))


Original Arr:
['Python PHP Java C++']
After Split :  [list(['Python', 'PHP', 'Java', 'C++'])]


----
#### Q3. Write a NumPy program to count the lowest index of "P" in a given array, element-wise.

In [50]:
arr = np.array(['Python', 'PHP', 'JS', 'examples', 'html'], dtype=str)
print("Original Arr:", arr)
print("Freq of P:", np.char.find(arr, "P"))

Original Arr: ['Python' 'PHP' 'JS' 'examples' 'html']
Freq of P: [ 0  0 -1 -1 -1]


----
#### Q4. Write a NumPy program to count a given word in each row of a given array of string values.

In [51]:
arr = np.array([['Python', 'NumPy', 'Exercises'],
                 ['Python', 'Pandas', 'Exercises'],
                 ['Python', 'Machine learning', 'Python']])
print("Original array: ", arr)
print("'Python' Freq:\n", np.char.count(arr, 'Python'))


Original array:  [['Python' 'NumPy' 'Exercises']
 ['Python' 'Pandas' 'Exercises']
 ['Python' 'Machine learning' 'Python']]
'Python' Freq:
 [[1 0 0]
 [1 0 0]
 [1 0 1]]


----
#### Q5. WAP to print max from axis 0 and min from axis 1 from the following 2-D array.

In [39]:
arr = np.array([[34, 43, 73],
                [82 ,22, 12],
                [53, 94 ,66]])
print(arr)
max = np.amax(arr, 0)
min= np.amin(arr, 1)
print("Maximum Values along axis 0: ", max)
print("Minimum Values along axis 1: ", min)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
Maximum Values along axis 0:  [82 94 73]
Minimum Values along axis 1:  [34 12 53]


----
#### Q6. WAP to delete the second column from a given array and insert the following new column in its place.

In [40]:
arr = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print("Array: ", arr)
arr = np.delete(arr , 1, axis = 1) 
print("Array after deleting column 2: ", arr)
col = np.array([[10,10,10]])
new = np.insert(arr , 1, col, axis = 1) 
print("Array after inserting column:\n", new)


Array:  [[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2:  [[34 73]
 [82 12]
 [53 66]]
Array after inserting column:
 [[34 10 73]
 [82 10 12]
 [53 10 66]]


----
#### Q7. WAP to Convert a 1-D array into a 2-D array with 3 rows

In [41]:
arr1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr2d= np.reshape(arr1d, (3, 3))
print("1D Array: ", arr1d)
print("2D Array:\n", arr2d)


1D Array:  [0 1 2 3 4 5 6 7 8]
2D Array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


----
#### Q8.WAP to generate a 1-D array of 10 random integers. Each integer should be a number between 30 and 40 (inclusive)

In [42]:
arr= np.random.randint(30,41, size=10)
print("Original Array: ", arr)

Original Array:  [31 39 40 37 34 35 31 37 36 30]


----
#### Q9. WAP to Replace all odd numbers in the given array with -1

In [43]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
for i in range(len(arr)):
    if arr[i] % 2 == 1:
        arr[i] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


----
#### Q10. WAP to create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

In [44]:
arr= np.arange(100,200,10).reshape(5,2)
print(arr)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]
