---
# <center> <b> TTL LAB 5 </b>

### Name: Ayush Priyam
### Roll: 20051933
### Date: 14th Feb 2023

---

### Importing numpy
and related modules

In [23]:
import numpy as np

---
### Q1. Write a program to create a null vector of size 25 but the values from fifth to tenth elements are all 1.

In [24]:
a = np.zeros(25, dtype=int)
a[4:10] = 1
print(a)

[0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


---
### Q2. Write a program to create a vector with values ranging from 5 to 20 & reverse it.

In [25]:
#n = int(input("Enter size: "))
n=10
a= np.random.randint(5,20, n)
print("Original array: ", a)
print("Flipped: ", np.flip(a))

Original array:  [12 14 12  6 16 13 18 10 11 11]
Flipped:  [11 11 10 18 13 16  6 12 14 12]


---
### Q3.Write a program to create a vector with 10 random values & sort first half ascending & second half descending.

In [26]:
n = 10
# a = np.zeros(n, dtype=int)
# for i in range(n):
#     a[i] = random.randint(0, 20000) % 50
a= np.random.randint(0,50,10)
print("Original array:", a)
x = np.sort(a[:5])
y = np.sort(a[5:])[::-1]
print("Modified array:",np.concatenate((x,y)))

Original array: [48  1 21 15 28 41 32 37 34 24]
Modified array: [ 1 15 21 28 48 41 37 34 32 24]


---
### Q4. Write a program to create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [27]:
n = 10
a = np.random.random(n)#can also use linspace
print(a)

[0.72624779 0.19668959 0.53380616 0.50343927 0.38047216 0.06452513
 0.78016599 0.51198874 0.48752787 0.53104713]


---
### Q5. Write a program to concatenate element-wise two arrays of string.  

In [28]:
n1 = "ayush"
n2 = "AAAAA"
a = np.array(list(n1))
b = np.array(list(n2))
x = []
for i in range(len(n1)):
    x.append(a[i]+b[i])
print(np.array(x))

['aA' 'yA' 'uA' 'sA' 'hA']


---
### Q6. WAP to create 4x3  and find max, min

In [29]:
a = np.random.randint(0, 50,(4, 3))
print("Array:\n", a)
print(f"Max:{np.max(a)}, Min:{np.min(a)} ")

Array:
 [[34 14 17]
 [28 23 45]
 [45 49 19]
 [40 11 17]]
Max:49, Min:11 


---
### Q7. Write a program to create a 2D array with 1 on the border and 0 inside.

In [30]:
a=np.ones((5,5), dtype=int)
a[1:-1,1:-1]=0
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

---
### Q8. Write a program to create a 4x4 matrix with values 1,2,3,4 just below & above the diagonal, rest zeros.

In [31]:
a = np.zeros((4, 4), int)
for i in range(1,4):
    a[i][i-1] = np.random.randint(1, 5)
    a[i-1][i] = np.random.randint(1, 5)
print(a)

[[0 2 0 0]
 [4 0 2 0]
 [0 1 0 2]
 [0 0 4 0]]


---
### Q9. Write a program to extract all the contiguous 3x3 blocks from a random 10x10 matrix. 

In [32]:
a = np.random.randint(0, 10,(10, 10))
print("Original array:\n", a)
print("All 3x3 blocks:")
for i in range(8):
    for j in range(8):
        print(a[i:i+3, j:j+3], end="\n\n")


Original array:
 [[4 2 2 4 0 8 1 7 8 0]
 [9 9 5 0 8 1 6 4 8 6]
 [1 9 1 5 5 1 8 1 6 4]
 [4 2 2 4 6 1 9 4 6 5]
 [1 1 8 8 0 7 8 2 8 0]
 [5 3 5 6 2 0 5 0 5 8]
 [6 4 1 9 7 3 2 8 6 5]
 [0 3 0 9 7 6 4 4 8 6]
 [3 5 4 5 6 7 1 3 2 9]
 [4 8 2 4 8 4 8 0 3 3]]
All 3x3 blocks:
[[4 2 2]
 [9 9 5]
 [1 9 1]]

[[2 2 4]
 [9 5 0]
 [9 1 5]]

[[2 4 0]
 [5 0 8]
 [1 5 5]]

[[4 0 8]
 [0 8 1]
 [5 5 1]]

[[0 8 1]
 [8 1 6]
 [5 1 8]]

[[8 1 7]
 [1 6 4]
 [1 8 1]]

[[1 7 8]
 [6 4 8]
 [8 1 6]]

[[7 8 0]
 [4 8 6]
 [1 6 4]]

[[9 9 5]
 [1 9 1]
 [4 2 2]]

[[9 5 0]
 [9 1 5]
 [2 2 4]]

[[5 0 8]
 [1 5 5]
 [2 4 6]]

[[0 8 1]
 [5 5 1]
 [4 6 1]]

[[8 1 6]
 [5 1 8]
 [6 1 9]]

[[1 6 4]
 [1 8 1]
 [1 9 4]]

[[6 4 8]
 [8 1 6]
 [9 4 6]]

[[4 8 6]
 [1 6 4]
 [4 6 5]]

[[1 9 1]
 [4 2 2]
 [1 1 8]]

[[9 1 5]
 [2 2 4]
 [1 8 8]]

[[1 5 5]
 [2 4 6]
 [8 8 0]]

[[5 5 1]
 [4 6 1]
 [8 0 7]]

[[5 1 8]
 [6 1 9]
 [0 7 8]]

[[1 8 1]
 [1 9 4]
 [7 8 2]]

[[8 1 6]
 [9 4 6]
 [8 2 8]]

[[1 6 4]
 [4 6 5]
 [2 8 0]]

[[4 2 2]
 [1 1 8]
 [5 3 5]]

[[2 2 4]
 [

---
### Q10. A magic square is a matrix all of whose row sums, column sums and the sums of the two diagonals are the same. (One diagonal of a matrix goes from the top left to the bottom right, the other diagonal goes from top right to bottom left.) 

Show by direct computation that if the matrix A is given by A=np.array([[17, 24, 1, 8, 15], [23, 5, 7, 14, 16], [ 4, 6, 13, 20, 22], [10, 12, 19, 21, 3], [11, 18, 25, 2, 9]]) The matrix A has 5 row sums (one for each row), 5 column sums (one for each column) and two diagonal sums. These 12 sums should all be exactly the same, and you could verify that they are the same by printing them and “seeing” that they are the same. It is easy to miss small differences among so many numbers, though. Instead, verify that A is a magic square by constructing the 5 column sums and computing the maximum and minimum values of the column sums. Do the same for the 5 row sums, and compute the two diagonal sums. Check that these six values are the same. If the maximum and minimum values are the same, the flyswatter principle says that all values are the same. Hints: The function np.diag extracts the diagonal of a matrix, and the function np.fliplr extracts the other diagonal

In [34]:
a=np.array([[17, 24, 1, 8, 15], 
        [23, 5, 7, 14, 16], 
        [ 4, 6, 13, 20, 22], 
        [10, 12, 19, 21, 3], 
        [11, 18, 25, 2, 9]])
rs= np.sum(a, 0)
print("Row sums: ",rs)
cs= np.sum(a,1)
print("Col sums: ", cs)
ds1= sum(np.diagonal(a))
ds2= sum(np.diagonal(np.fliplr(a)))
print("Diag sums= ", ds1, ds2)
if ds1== ds2 and ds2== rs.max() and rs.max() == rs.min() and rs.min()== cs.max() and cs.max()== cs.min():
    print("Magic matrix")
else:
    print("Not magic")
    

Row sums:  [65 65 65 65 65]
Col sums:  [65 65 65 65 65]
Diag sums=  65 65
Magic matrix
